// Run: NODE_PATH=<directory containing playwright> node tests/prototype.cjs
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true,channel:"chrome"});
  try {
    const page = await browser.newPage({viewport:{width:1280,height:1000}});
    page.setDefaultTimeout(2500);
    const errors=[]; page.on('pageerror', e=>errors.push(e.message));
    await page.goto(pathToFileURL(path.resolve(__dirname,'../AudioPatch-交互原型.html')).href);
    const screen = () => page.locator('.screen.on');
    await screen().locator('[data-go="s08"]').first().click();
    assert(await screen().getByRole('button',{name:'先选择一句',exact:true}).isDisabled(), 'No implicit recording target');
    await screen().locator('[data-seg="sg02"]').click();
    await screen().getByRole('button',{name:'重录第 2 句',exact:true}).click();
    assert.match(await screen().locator('h2').innerText(), /第 2 句/);
    assert.match(await screen().innerText(), /我们带来的作品叫 AudioPatch/);
    console.log('PASS: unselected state and recording target');
    assert.equal(await screen().locator('#recStates').isVisible(),false);
    await screen().getByRole('button',{name:'开始重录',exact:true}).click();
    assert(await screen().getByRole('button',{name:'请等待倒计时',exact:true}).isDisabled());
    await screen().getByRole('button',{name:'停止并保存候选',exact:true}).waitFor({timeout:5000});
    await screen().getByRole('button',{name:'停止并保存候选',exact:true}).click();
    assert.match(await screen().innerText(), /当前使用：原始录音/);
    await screen().getByRole('button',{name:'返回',exact:true}).click();
    await screen().getByRole('button',{name:'修改文字',exact:true}).click();
    await screen().locator('#editText').fill('第二句改字 <测试>');
    await screen().getByRole('button',{name:'保存文字',exact:true}).click();
    assert.match(await screen().locator('[data-seg="sg02"]').innerText(), /第二句改字 <测试>/);
    await screen().getByRole('button',{name:'导出',exact:true}).click();
    assert.equal(await screen().locator('h2').innerText(),'检查并确认');
    await screen().locator('[data-id="sg02"][data-check="text"]').check();
    assert(await screen().getByRole('button',{name:'完成检查后继续导出'}).isDisabled());
    for(const id of ['sg02','sg07','sg10']) {
      await screen().locator(`[data-id="${id}"][data-check="text"]`).check();
      await screen().locator(`[data-id="${id}"][data-check="range"]`).check();
    }
    await screen().getByRole('button',{name:'继续导出',exact:true}).click();
    assert.equal(await screen().locator('h2').innerText(),'导出成片');
    await screen().locator('#exportFormat').selectOption('wav');
    assert.match(await screen().locator('#exportName').inputValue(), /\.wav$/);
    await screen().getByRole('button',{name:'模拟导出',exact:true}).click();
    await screen().getByText('模拟导出完成',{exact:true}).waitFor({timeout:5000});
    await screen().getByRole('button',{name:'回到项目继续编辑',exact:true}).click();
    await screen().locator('[data-seg="sg09"]').click();
    await screen().getByRole('button',{name:'更多操作',exact:true}).click();
    await screen().getByRole('button',{name:'比较补录版本',exact:true}).click();
    await screen().locator('input[value="v1"]').check();
    assert.match(await screen().innerText(), /当前使用：v2/);
    await screen().getByRole('button',{name:'试听前后文',exact:true}).click();
    assert.match(await screen().innerText(), /v1（候选，未采用）/);
    await screen().getByRole('button',{name:'回到版本比较',exact:true}).click();
    assert(await screen().locator('input[value="v1"]').isChecked());
    await screen().getByRole('button',{name:'使用此版本',exact:true}).click();
    await screen().getByRole('button',{name:'试听完整成片',exact:true}).click();
    assert.match(await screen().innerText(), /01:12.2/);
    await screen().getByRole('button',{name:'返回',exact:true}).click();
    await screen().getByRole('button',{name:'更多操作',exact:true}).click();
    await screen().getByRole('button',{name:'恢复这一句的原始录音',exact:true}).click();
    await screen().getByRole('button',{name:'试听完整成片',exact:true}).click();
    assert.match(await screen().innerText(), /已替换 0 句话/);
    assert.match(await screen().innerText(), /成片时长：01:15.6/);
    await screen().getByRole('button',{name:'返回',exact:true}).click();
    await screen().locator('[data-seg="sg07"]').click();
    await screen().getByRole('button',{name:'修改文字',exact:true}).click();
    await screen().locator('#editText').fill('改过的第七句');
    await screen().getByRole('button',{name:'保存文字',exact:true}).click();
    await screen().getByRole('button',{name:'导出',exact:true}).click();
    assert.equal(await screen().locator('h2').innerText(),'检查并确认');
    assert.equal(await screen().locator('[data-id="sg07"][data-check="text"]').isChecked(),false);
    assert.equal(await screen().locator('[data-id="sg07"][data-check="range"]').isChecked(),false);
    // Demonstration navigation must not bypass the same export gate.
    await page.locator('#modeBtn').click();
    await page.locator('#nav [data-go="s19"]').click();
    assert.equal(await screen().locator('h2').innerText(),'检查并确认');
    await page.locator('#modeBtn').click();
    console.log('PASS: text edit, two-part confirmation, export gate, version adoption and restoration');
    await page.screenshot({path:'/tmp/audiopatch-review.png'});
    await page.setViewportSize({width:390,height:844});
    await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await page.screenshot({path:'/tmp/audiopatch-mobile.png'});
    console.log('PASS: mobile document has no horizontal overflow');
    // Optional inputs remain editable; arrow keys must not navigate away.
    await page.reload();
    await screen().getByRole('button',{name:'新建项目',exact:true}).click();
    await screen().locator('summary').click();
    await screen().locator('#outlineInput').fill('第一点：介绍作品');
    await screen().locator('#outlineInput').press('ArrowLeft');
    assert.equal(await screen().locator('h2').innerText(),'新建项目');
    await screen().getByRole('button',{name:/完整录制/}).click();
    assert.match(await screen().innerText(),/第一点：介绍作品/);
    await screen().getByRole('button',{name:'暂停',exact:true}).click();
    const paused=await screen().locator('#recTime').innerText();
    await page.waitForTimeout(250);
    assert.equal(await screen().locator('#recTime').innerText(),paused);
    await page.setViewportSize({width:1280,height:1000});
    await page.locator('#modeBtn').click();
    await page.locator('#viewBtn [data-view="gal"]').click();
    assert.equal(await page.locator('.gal-item').count(),21);
    await page.locator('.gal-item[data-screen="s15"]').click();
    assert.equal(await screen().locator('h2').innerText(),'挑战杯 · 作品介绍');
    assert.deepEqual(errors,[]);
    console.log('PASS: optional inputs, pause, gallery and zero page errors');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
